In [1]:
!pip install faker
!pip install randomtimestamp

Collecting faker
  Downloading faker-37.1.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from faker) (2025.1)
Downloading faker-37.1.0-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 18.6 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-37.1.0
Collecting randomtimestamp
  Downloading randomtimestamp-2.2-py3-none-any.whl.metadata (5.5 kB)
Downloading randomtimestamp-2.2-py3-none-any.whl (19 kB)
Installing collected packages: randomtimestamp
Successfully installed randomtimestamp-2.2

In [2]:
from faker import Faker
import random
import pandas as pd
from datetime import datetime, timedelta

In [3]:
now = datetime.now()
min_date = now - timedelta(days=10)

fake = Faker()
n = 10000

employees = []
for _ in range(n):
    employee = {
        'id': _,
        'name': fake.name(),
        'email': fake.email(),
        'telephone': random.randint(9000000000, 9999999999),
        'address': fake.address(),
        'last_check_in': pd.to_datetime(pd.date_range(min_date, now, periods=1).values[0]),
        'department': fake.random_element(elements=('Sales', 'Marketing', 'IT', 'HR')),
        'salary': random.randint(20000 // 5000, 150000 // 5000) * 5000,
        'age': random.randint(20, 70),
        'managers_id': None,
        'position': None,
        'relatives_id': random.randint(0, n) if fake.boolean(chance_of_getting_true=20) else None,
        'start_date': str(fake.date_between(start_date='-10y', end_date='today')),
        'end_date': str(fake.date_between(start_date='-5y', end_date='today')) if fake.boolean(chance_of_getting_true=5) else None
    }
    employees.append(employee)

In [4]:
df = pd.DataFrame.from_dict(employees)

In [6]:
df.loc[df['id']==999, 'position'] = 'General Director'
df.loc[df['id']==999, 'managers_id'] = 999
df.loc[df['id']==999, 'department'] = 'HEAD'
df.loc[df['id']==998, 'position'] = 'Vice General Director'
df.loc[df['id']==998, 'managers_id'] = 999
df.loc[df['id']==998, 'department'] = 'HEAD'

In [7]:
dict_hierarchy = {'Sales': [['Head of department', 11, 998],
                            ['Vice-Head of department', 5249, 11],
                            ['Director', 3759, 5249],
                            ['Director', 2734, 5249],
                            ['Director', 4444, 5249],
                            ['Director', 24, 5249],
                            ['Director', 2546, 5249],
                            ['Lead Specialist', 1000, 3759],
                            ['Lead Specialist', 1001, 3759],
                            ['Lead Specialist', 1005, 3759],
                            ['Lead Specialist', 1006, 2734],
                            ['Lead Specialist', 1010, 2734],
                            ['Lead Specialist', 1011, 2734],
                            ['Lead Specialist', 1012, 4444],
                            ['Lead Specialist', 1013, 4444],
                            ['Lead Specialist', 1014, 24],
                            ['Lead Specialist', 1015, 24],
                            ['Lead Specialist', 1016, 2546],
                            ['Lead Specialist', 1017, 2546],
                            ['Senior Specialist', 1100, 1000],
                            ['Senior Specialist', 1101, 1000],
                            ['Senior Specialist', 1102, 1001],
                            ['Senior Specialist', 1103, 1005],
                            ['Senior Specialist', 1104, 1006],
                            ['Senior Specialist', 1105, 1006],
                            ['Senior Specialist', 1106, 1010],
                            ['Senior Specialist', 1107, 1011],
                            ['Senior Specialist', 1108, 1012],
                            ['Senior Specialist', 1109, 1012],
                            ['Senior Specialist', 1110, 1012],
                            ['Senior Specialist', 1111, 1013],
                            ['Senior Specialist', 1112, 1014],
                            ['Senior Specialist', 1113, 1014],
                            ['Senior Specialist', 1114, 1014],
                            ['Senior Specialist', 1115, 1015],
                            ['Senior Specialist', 1116, 1016],
                            ['Senior Specialist', 1117, 1017],
                            ['Manager', 1200, 1100],
                            ['Manager', 1201, 1100],
                            ['Manager', 1202, 1101],
                            ['Manager', 1203, 1101],
                            ['Manager', 1204, 1102],
                            ['Manager', 1205, 1102],
                            ['Manager', 1206, 1103],
                            ['Manager', 1207, 1103],
                            ['Manager', 1208, 1104],
                            ['Manager', 1209, 1104],
                            ['Manager', 1210, 1105],
                            ['Manager', 1211, 1105],
                            ['Manager', 1212, 1106],
                            ['Manager', 1213, 1106],
                            ['Manager', 1214, 1107],
                            ['Manager', 1215, 1107],
                            ['Manager', 1216, 1108],
                            ['Manager', 1217, 1108],
                            ['Manager', 1218, 1109],
                            ['Manager', 1219, 1109],
                            ['Manager', 1220, 1110],
                            ['Manager', 1221, 1110],
                            ['Manager', 1222, 1111],
                            ['Manager', 1223, 1111],
                            ['Manager', 1224, 1112],
                            ['Manager', 1225, 1112],
                            ['Manager', 1226, 1113],
                            ['Manager', 1227, 1113],
                            ['Manager', 1228, 1114],
                            ['Manager', 1229, 1114],
                            ['Manager', 1230, 1014],
                            ['Manager', 1231, 1014],
                            ['Manager', 1232, 1115],
                            ['Manager', 1233, 1115],
                            ['Manager', 1234, 1116],
                            ['Manager', 1235, 1117]],
                  'Marketing': [['Head of department', 21, 998],
                            ['Vice-Head of department', 6249, 21],
                            ['Director', 4759, 6249],
                            ['Director', 3734, 6249],
                            ['Director', 5444, 6249],
                            ['Director', 34, 6249],
                            ['Director', 3546, 6249],
                            ['Lead Specialist', 2000, 4759],
                            ['Lead Specialist', 2001, 4759],
                            ['Lead Specialist', 2005, 4759],
                            ['Lead Specialist', 2006, 3734],
                            ['Lead Specialist', 2010, 3734],
                            ['Lead Specialist', 2011, 3734],
                            ['Lead Specialist', 2012, 5444],
                            ['Lead Specialist', 2013, 5444],
                            ['Lead Specialist', 2014, 34],
                            ['Lead Specialist', 2015, 34],
                            ['Lead Specialist', 2016, 3546],
                            ['Lead Specialist', 2017, 3546],
                            ['Senior Specialist', 2100, 2000],
                            ['Senior Specialist', 2101, 2000],
                            ['Senior Specialist', 2102, 2001],
                            ['Senior Specialist', 2103, 2005],
                            ['Senior Specialist', 2104, 2006],
                            ['Senior Specialist', 2105, 2006],
                            ['Senior Specialist', 2106, 2010],
                            ['Senior Specialist', 2107, 2011],
                            ['Senior Specialist', 2108, 2012],
                            ['Senior Specialist', 2109, 2012],
                            ['Senior Specialist', 2110, 2012],
                            ['Senior Specialist', 2111, 2013],
                            ['Senior Specialist', 2112, 2014],
                            ['Senior Specialist', 2113, 2014],
                            ['Senior Specialist', 2114, 2014],
                            ['Senior Specialist', 2115, 2015],
                            ['Senior Specialist', 2116, 2016],
                            ['Senior Specialist', 2117, 2017],
                            ['Manager', 2200, 2100],
                            ['Manager', 2201, 2100],
                            ['Manager', 2202, 2101],
                            ['Manager', 2203, 2101],
                            ['Manager', 2204, 2102],
                            ['Manager', 2205, 2102],
                            ['Manager', 2206, 2103],
                            ['Manager', 2207, 2103],
                            ['Manager', 2208, 2104],
                            ['Manager', 2209, 2104],
                            ['Manager', 2210, 2105],
                            ['Manager', 2211, 2105],
                            ['Manager', 2212, 2106],
                            ['Manager', 2213, 2106],
                            ['Manager', 2214, 2107],
                            ['Manager', 2215, 2107],
                            ['Manager', 2216, 2108],
                            ['Manager', 2217, 2108],
                            ['Manager', 2218, 2109],
                            ['Manager', 2219, 2109],
                            ['Manager', 2220, 2110],
                            ['Manager', 2221, 2110],
                            ['Manager', 2222, 2111],
                            ['Manager', 2223, 2111],
                            ['Manager', 2224, 2112],
                            ['Manager', 2225, 2112],
                            ['Manager', 2226, 2113],
                            ['Manager', 2227, 2113],
                            ['Manager', 2228, 2114],
                            ['Manager', 2229, 2114],
                            ['Manager', 2230, 2014],
                            ['Manager', 2231, 2014],
                            ['Manager', 2232, 2115],
                            ['Manager', 2233, 2115],
                            ['Manager', 2234, 2116],
                            ['Manager', 2235, 2117]],
                  'IT': [['Head of department', 31, 998],
                            ['Vice-Head of department', 3249, 31],
                            ['Director', 7759, 3249],
                            ['Director', 7734, 3249],
                            ['Director', 7444, 3249],
                            ['Director', 74, 3249],
                            ['Director', 7546, 3249],
                            ['Lead Specialist', 3000, 7759],
                            ['Lead Specialist', 3001, 7759],
                            ['Lead Specialist', 3005, 7759],
                            ['Lead Specialist', 3006, 7734],
                            ['Lead Specialist', 3010, 7734],
                            ['Lead Specialist', 3011, 7734],
                            ['Lead Specialist', 3012, 7444],
                            ['Lead Specialist', 3013, 7444],
                            ['Lead Specialist', 3014, 74],
                            ['Lead Specialist', 3015, 74],
                            ['Lead Specialist', 3016, 7546],
                            ['Lead Specialist', 3017, 7546],
                            ['Senior Specialist', 3100, 3000],
                            ['Senior Specialist', 3101, 3000],
                            ['Senior Specialist', 3102, 3001],
                            ['Senior Specialist', 3103, 3005],
                            ['Senior Specialist', 3104, 3006],
                            ['Senior Specialist', 3105, 3006],
                            ['Senior Specialist', 3106, 3010],
                            ['Senior Specialist', 3107, 3011],
                            ['Senior Specialist', 3108, 3012],
                            ['Senior Specialist', 3109, 3012],
                            ['Senior Specialist', 3110, 3012],
                            ['Senior Specialist', 3111, 3013],
                            ['Senior Specialist', 3112, 3014],
                            ['Senior Specialist', 3113, 3014],
                            ['Senior Specialist', 3114, 3014],
                            ['Senior Specialist', 3115, 3015],
                            ['Senior Specialist', 3116, 3016],
                            ['Senior Specialist', 3117, 3017],
                            ['Manager', 3200, 3100],
                            ['Manager', 3201, 3100],
                            ['Manager', 3202, 3101],
                            ['Manager', 3203, 3101],
                            ['Manager', 3204, 3102],
                            ['Manager', 3205, 3102],
                            ['Manager', 3206, 3103],
                            ['Manager', 3207, 3103],
                            ['Manager', 3208, 3104],
                            ['Manager', 3209, 3104],
                            ['Manager', 3210, 3105],
                            ['Manager', 3211, 3105],
                            ['Manager', 3212, 3106],
                            ['Manager', 3213, 3106],
                            ['Manager', 3214, 3107],
                            ['Manager', 3215, 3107],
                            ['Manager', 3216, 3108],
                            ['Manager', 3217, 3108],
                            ['Manager', 3218, 3109],
                            ['Manager', 3219, 3109],
                            ['Manager', 3220, 3110],
                            ['Manager', 3221, 3110],
                            ['Manager', 3222, 3111],
                            ['Manager', 3223, 3111],
                            ['Manager', 3224, 3112],
                            ['Manager', 3225, 3112],
                            ['Manager', 3226, 3113],
                            ['Manager', 3227, 3113],
                            ['Manager', 3228, 3114],
                            ['Manager', 3229, 3114],
                            ['Manager', 3230, 3014],
                            ['Manager', 3231, 3014],
                            ['Manager', 3232, 3115],
                            ['Manager', 3233, 3115],
                            ['Manager', 3234, 3116],
                            ['Manager', 3235, 3117]],
                  'HR': [['Head of department', 81, 998],
                            ['Vice-Head of department', 8249, 81],
                            ['Director', 8759, 8249],
                            ['Director', 8734, 8249],
                            ['Director', 8444, 8249],
                            ['Director', 84, 8249],
                            ['Director', 8546, 8249],
                            ['Lead Specialist', 8000, 8759],
                            ['Lead Specialist', 8001, 8759],
                            ['Lead Specialist', 8005, 8759],
                            ['Lead Specialist', 8006, 8734],
                            ['Lead Specialist', 8010, 8734],
                            ['Lead Specialist', 8011, 8734],
                            ['Lead Specialist', 8012, 8444],
                            ['Lead Specialist', 8013, 8444],
                            ['Lead Specialist', 8014, 84],
                            ['Lead Specialist', 8015, 84],
                            ['Lead Specialist', 8016, 8546],
                            ['Lead Specialist', 8017, 8546],
                            ['Senior Specialist', 8100, 8000],
                            ['Senior Specialist', 8101, 8000],
                            ['Senior Specialist', 8102, 8001],
                            ['Senior Specialist', 8103, 8005],
                            ['Senior Specialist', 8104, 8006],
                            ['Senior Specialist', 8105, 8006],
                            ['Senior Specialist', 8106, 8010],
                            ['Senior Specialist', 8107, 8011],
                            ['Senior Specialist', 8108, 8012],
                            ['Senior Specialist', 8109, 8012],
                            ['Senior Specialist', 8110, 8012],
                            ['Senior Specialist', 8111, 8013],
                            ['Senior Specialist', 8112, 8014],
                            ['Senior Specialist', 8113, 8014],
                            ['Senior Specialist', 8114, 8014],
                            ['Senior Specialist', 8115, 8015],
                            ['Senior Specialist', 8116, 8016],
                            ['Senior Specialist', 8117, 8017],
                            ['Manager', 8200, 8100],
                            ['Manager', 8201, 8100],
                            ['Manager', 8202, 8101],
                            ['Manager', 8203, 8101],
                            ['Manager', 8204, 8102],
                            ['Manager', 8205, 8102],
                            ['Manager', 8206, 8103],
                            ['Manager', 8207, 8103],
                            ['Manager', 8208, 8104],
                            ['Manager', 8209, 8104],
                            ['Manager', 8210, 8105],
                            ['Manager', 8211, 8105],
                            ['Manager', 8212, 8106],
                            ['Manager', 8213, 8106],
                            ['Manager', 8214, 8107],
                            ['Manager', 8215, 8107],
                            ['Manager', 8216, 8108],
                            ['Manager', 8217, 8108],
                            ['Manager', 8218, 8109],
                            ['Manager', 8219, 8109],
                            ['Manager', 8220, 8110],
                            ['Manager', 8221, 8110],
                            ['Manager', 8222, 8111],
                            ['Manager', 8223, 8111],
                            ['Manager', 8224, 8112],
                            ['Manager', 8225, 8112],
                            ['Manager', 8226, 8113],
                            ['Manager', 8227, 8113],
                            ['Manager', 8228, 8114],
                            ['Manager', 8229, 8114],
                            ['Manager', 8230, 8014],
                            ['Manager', 8231, 8014],
                            ['Manager', 8232, 8115],
                            ['Manager', 8233, 8115],
                            ['Manager', 8234, 8116],
                            ['Manager', 8235, 8117]]}

In [8]:
for department, dep_data in dict_hierarchy.items():
  for employee in dep_data:
    df.loc[df['id']==employee[1], 'managers_id'] = employee[2]
    df.loc[df['id']==employee[1], 'department'] = department
    df.loc[df['id']==employee[1], 'position'] = employee[0]

In [9]:
marketing_managers = set(df[(df['position'] == 'Manager') & (df['department'] == 'Marketing')]['id'].tolist())
sales_managers = set(df[(df['position'] == 'Manager') & (df['department'] == 'Sales')]['id'].tolist())
hr_managers = set(df[(df['position'] == 'Manager') & (df['department'] == 'HR')]['id'].tolist())
it_managers = set(df[(df['position'] == 'Manager') & (df['department'] == 'IT')]['id'].tolist())

In [10]:
employees = []
for i in range(len(df)):
  if (df['department'][i] == 'Marketing') and (df['managers_id'][i] == None):
    employees.append(fake.random_element(elements=marketing_managers))
  elif (df['department'][i] == 'Sales') and (pd.isna(df['managers_id'][i])):
    employees.append(fake.random_element(elements=sales_managers))
  elif (df['department'][i] == 'HR') and (pd.isna(df['managers_id'][i])):
    employees.append(fake.random_element(elements=hr_managers))
  elif (df['department'][i] == 'IT') and (pd.isna(df['managers_id'][i])):
    employees.append(fake.random_element(elements=it_managers))
  else:
    employees.append(df['managers_id'][i])

In [11]:
df['managers_id'] = employees

In [12]:
df.loc[df['position'].isna(), 'position'] = 'Specialist'

In [14]:
df

,id,name,email,telephone,address,last_check_in,department,salary,age,managers_id,position,relatives_id,start_date,end_date
0,0,James Johnson,olsenmary@example.com,9463860658,"6032 Jocelyn Junctions\nNew Wyattburgh, MO 97330",2025-03-15 12:00:21.708364,Marketing,70000,26,2232,Specialist,8465.0,2021-11-29,None
1,1,Edward Stout,patriciabernard@example.org,9838072358,"855 Patrick Drive\nHarpermouth, NH 36462",2025-03-15 12:00:21.708364,Sales,95000,52,1217,Specialist,NaN,2017-09-28,None
2,2,Dr. Luis Henry,nelsonrobert@example.org,9126490026,USCGC Price\nFPO AP 46158,2025-03-15 12:00:21.708364,HR,50000,38,8222,Specialist,NaN,2022-12-22,None
3,3,Christopher Hart,alyssadominguez@example.org,9069207734,USNS Smith\nFPO AP 93964,2025-03-15 12:00:21.708364,Marketing,35000,47,2226,Specialist,NaN,2020-02-12,None
4,4,Casey Flores,wrightricky@example.net,9274634116,"71876 Julie Shoals\nDylanshire, ME 39266",2025-03-15 12:00:21.708364,Sales,130000,60,1200,Specialist,118.0,2024-09-04,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,Lynn Horton,candice92@example.org,9288664733,"695 Whitehead Manor\nSouth Christinaton, VT 36937",2025-03-15 12:00:21.708364,IT,95000,67,3202,Specialist,NaN,2020-07-18,None
9996,9996,James Johnson,coxalyssa@example.net,9293885421,"874 Krystal Port Suite 613\nWest Rodneyfort, N...",2025-03-15 12:00:21.708364,Sales,95000,46,1202,Specialist,NaN,2023-08-10,None
9997,9997,Logan Whitaker,hartstephen@example.com,9583140697,"3697 Holmes Cove\nNorth Rachel, WA 67039",2025-03-15 12:00:21.708364,Sales,95000,49,1211,Specialist,NaN,2024-10-05,None
9998,9998,Joshua Marshall,bradtorres@example.com,9004832526,"217 Chad Course\nKristinside, PW 67535",2025-03-15 12:00:21.708364,IT,150000,59,3202,Specialist,NaN,2020-07-08,None
9999,9999,Amy James,sarahbradford@example.org,9547173618,"1802 Clark Plaza\nColonhaven, AK 23032",2025-03-15 12:00:21.708364,HR,110000,31,8218,Specialist,NaN,2020-05-13,None

In [13]:
df.to_csv('employees_project.csv')